#!/bin/bash

if ! which pacman > /dev/null 2>&1; then
	echo "Huh, it is not an Arch Linux, man..."
	exit 0
fi

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
KERNEL="linux,linux-headers,virtualbox-host-modules-arch"
IGNORE="mesa,llvm-libs,clang"
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

mkdir -p ~/work
LOG=~/work/arch-update-$(date +%y-%m-%d-%T)-$$.log

if [ "$1" == "-h" ]; then
	echo "$(basename $0) [-n] [-i|-A|-f|<list_of_packages_to_be_updated>]"
	echo "   Update all packages except of: $KERNEL"
	echo "   -i - update all packages except of: $KERNEL, $IGNORE"
	echo "   -A - update ALL packages"
	echo "   -f - force AUR update"
	echo "   -n - dry run"
	exit 0
fi

[ "$1" == "-n" ] && DRY_RUN=YES && shift

case $1 in
"-A")
	IGNORE=""
	;;
"-i")
	IGNORE="--ignore $KERNEL,$IGNORE"
	;;
*)
	IGNORE="--ignore $KERNEL"
	;;
esac

case $1 in
""|"-i"|"-A"|"-f")
	OPT="-Syu"
	;;
*)
	OPT="-S $*"
	;;
esac

CMD="sudo -E pacman $OPT --color always --logfile $LOG $IGNORE"

echo $CMD
[ "$DRY_RUN" == "YES" ] && exit 0
eval $CMD

if [ -f $LOG ]; then
	if [ $(cat $LOG | wc -l) -le 3 ]; then
		rm -f $LOG
		echo " Removed empty log"
	else
		sudo chown $(whoami).$(whoami) $LOG
	fi
fi

echo
echo ":: Updating AUR packages..."
mkdir -p ~/aur
cd ~/aur
for pkg in $(ls -1); do
	echo "* $pkg:"
	arch-aur $pkg $1
	if [ $? -ne 0 -a "$1" != "-f" ]; then
		echo "^^^^^^^ FAILED ^^^^^^^"
		echo
		echo "******* Retrying with FORCE *******"
		echo "* $pkg:"
		arch-aur $pkg -f
	fi
done

HOST=$(hostname | cut -d. -f1)
echo

if [ -d ~/work ]; then
	echo ":: Saving list of packages..."
	ALL_PACKAGES=~/work/pacman-all-packages.txt
	pacman -Q | cut -d' ' -f1 > $ALL_PACKAGES
	for f in $(pacman -Ql mesa | grep nouveau | cut -d' ' -f2 | xargs); do
		pacman -Qo $f >> $ALL_PACKAGES
	done
	echo "List of packages saved to: $ALL_PACKAGES"

	if [ -d ~/work/mytools/config/pacman-pkg ]; then
		DIR=~/work/mytools/config/pacman-pkg/${HOST}/
		mkdir -p $DIR
		cp -f $ALL_PACKAGES $DIR
	fi
fi

echo ":: Pruning cache of packages..."
sudo paccache -r

echo ":: Checking database of packages..."
sudo pacman -D -k

echo ":: Checking packages..."
ERR=/tmp/pacman.err
sudo pacman -Q --check 2>$ERR | grep -v -e "0 missing files"
if [ $(cat $ERR | wc -l) -gt 0 ]; then
	cat $ERR
else
	echo "No errors found"
fi

echo ":: New config files:"
NEW=/tmp/pacman.new
sudo find /etc -iname "*.pacnew" > $NEW
if [ -f $LOG ] && [ $(cat $LOG | grep -e '.pacnew' | wc -l) -gt 0 ]; then
	cat $LOG | grep -e '.pacnew'
elif [ -f $NEW ] && [ $(cat $NEW | wc -l) -gt 0 ]; then
	echo "   (sudo find /etc -iname '*.pacnew'):"
	cat $NEW
else
	echo "No new config files found"
fi

