#!/bin/bash

# REPO=$(git remote -v | grep -e origin | grep -e fetch | sed 's/.*\///g' | sed 's/.git//g' | cut -d' ' -f1)
# [ "$REPO" != "" ] && echo $REPO && exit 0

while [ ! -d .git ]; do
	cd ..
	[ "$(pwd)" == "/" ] && exit 1
done

basename $(pwd)
