#!/bin/bash

DIR=$(git-get-current-repo-dir 2>/dev/null)
[ "$DIR" == "" ] && exit 1

FILE=$DIR/.git/default-branches
if [ -f $FILE ]; then
	cat $FILE | grep -v -e '#' | cut -d" " -f1
	exit 0
fi

DEFAULT_BRANCHES="main master"

for branch in $DEFAULT_BRANCHES; do
	if git log -1 origin/$branch >/dev/null 2>&1; then
		echo "$branch"
		exit 0
	fi
done

echo "unknown"
